apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: variables-spinapp
spec:
  image: "ghcr.io/spin-kube/vars:v1"
  replicas: 1
  executor: containerd-shim-spin
  variables:
    - name: greetee
      value: Fermyon
